const carCollection = [
  {
    id: 0,
    brand: "Range Rover Velar",
    url: "https://i.ibb.co/txZKmYd/range-Rover.webp",
    model: "2019 model",
    type: "Sport Utility",
    miles: "21,853",
    exterior: "White",
    interior: "Charcoal",
    engine: "6 Cylinders 3.0L",
    fuel: "Octen, Petrol, Diesel",
    price: "3 Crore",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 1,
    brand: "Lucid Air",
    url: "https://i.ibb.co/jTg2Gfv/lucid.png",
    model: "2020 model",
    type: "Sedan",
    miles: "22,211",
    exterior: "Cream White",
    interior: "Charcoal",
    engine: "2 Cylinders 2.0L",
    fuel: "Octen, Diesel",
    price: "70 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 2,
    brand: "Audi Q8",
    url: "https://i.ibb.co/XbfBqx2/audiQ8.png",
    model: "2019 model",
    type: "Sport Utility",
    miles: "15020",
    exterior: "Carrara White",
    interior: "Carbon Fibre",
    engine: "6 Cylinders 3.0L",
    fuel: "Octen, Petrol, Diesel",
    price: "2 Crore 20 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 3,
    brand: "Tesla Model 3",
    url: "https://i.ibb.co/kDXk1Sc/tesla.png",
    model: "2020 model",
    type: "Sedan",
    miles: "33,283",
    exterior: "White",
    interior: "Charcoal",
    engine: "1 Cylinders",
    fuel: "Octen, Petrol",
    price: "1 Crore",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 4,
    brand: "Maserati",
    url: "https://i.ibb.co/FJ4n3Zd/Maserati.png",
    model: "2017 model",
    type: "Sedan",
    miles: "32,500",
    exterior: "Silver",
    interior: "Carbon",
    engine: "2 Cylinder",
    fuel: "Octen, Diesel",
    price: "1 Crore, 2 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 5,
    brand: "Audi A5",
    url: "https://i.ibb.co/tb430N0/audi.png",
    model: "2019 model",
    type: "Sedan",
    miles: "3,950",
    exterior: "White",
    interior: "Carbon",
    engine: "3 Cylinder",
    fuel: "Octen, Diesel, Petrol",
    price: "1 Crore 3 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 6,
    brand: "Mercedes AMG GT63",
    url: "https://i.ibb.co/zscX6CJ/mercedes-Amg.png",
    model: "2020 model",
    type: "Sedan",
    miles: "10,000",
    exterior: "Matt Black",
    interior: "Charcoal",
    engine: "2 Cylinders 2 Gallons",
    fuel: "Petrol, Octen, Diesel",
    price: "1 Crore 50 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 7,
    brand: "Toyota Land Cruiser Prado",
    url: "https://i.ibb.co/nmw22mL/land-Cruiser.png",
    model: "2020 model",
    type: "Sport Utility",
    miles: "9,845",
    exterior: "Silver",
    interior: "Carbon",
    engine: "4 Cylinders 2.0L",
    fuel: "Octen, Petrol, Diesel",
    price: "3 Crore",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 8,
    brand: "Audi A8",
    url: "https://i.ibb.co/MSy51QD/audiA8.png",
    model: "2019 model",
    type: "Sedan",
    miles: "8,040",
    exterior: "Florett Silver",
    interior: "Charcoal",
    engine: "6 Cylinders 3.0L",
    fuel: "Octen, Petrol, Diesel",
    price: "2 Crore",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  },
  {
    id: 9,
    brand: "Toyota Harier",
    url: "https://i.ibb.co/M8XbvHx/harier.png",
    model: "2017 model",
    type: "Sport Utility",
    miles: "71,229",
    exterior: "Jet Black",
    interior: "Carbon Fibre",
    engine: "6 Cylinders 4.0L",
    fuel: "Petrol, Diesel, Octen",
    price: "70 Lac",
    transmission: "Automatic",
    drive: "AWD / 4WD"
  }
]